spring:
  application:
    name: nullang
spring:
  output:
    ansi:
      enabled: always
logging:
  file:
    name: logs/application.log
  level:
    root: INFO
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p){highlight} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan} : %m%n%wex"
